from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
import os


def generate_certificate(user_name, course_name):

    folder = "certificates"

    os.makedirs(folder, exist_ok=True)

    filename = f"{user_name}_{course_name}.pdf".replace(" ", "_")

    filepath = os.path.join(folder, filename)

    doc = SimpleDocTemplate(filepath)

    styles = getSampleStyleSheet()

    story = []

    story.append(Paragraph("<b>CERTIFICATE OF COMPLETION</b>", styles["Title"]))

    story.append(Spacer(1, 30))

    story.append(
        Paragraph(
            f"This certifies that <b>{user_name}</b>",
            styles["Heading2"],
        )
    )

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            f"has successfully completed the course",
            styles["BodyText"],
        )
    )

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            f"<b>{course_name}</b>",
            styles["Heading1"],
        )
    )

    story.append(Spacer(1, 30))

    story.append(
        Paragraph(
            "Generated by EduAgent AI",
            styles["Italic"],
        )
    )

    doc.build(story)

    return filepath