from database.database import SessionLocal
from database.crud import create_course

db = SessionLocal()

course = create_course(
    db=db,
    user_id=1,
    title="Operating Systems",
    description="Generated by EduAgent AI"
)

print(course.id)
print(course.title)